services:
  traefik:
    image: traefik:v2.11
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - web

  frontend:
    build:
      context: ./frontend
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - web

  user-service:
    build:
      context: ./user-service
    environment:
      DATABASE_URL: ${USER_DATABASE_URL}
      PORT: ${USER_SERVICE_PORT}
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=PathPrefix(`/api/users`)"
      - "traefik.http.routers.users.middlewares=users-strip@docker"
      - "traefik.http.middlewares.users-strip.stripprefix.prefixes=/api/users"
      - "traefik.http.services.users.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik-project_web"
    networks:
      - web
      - backend

  product-service:
    build:
      context: ./product-service
    environment:
      DATABASE_URL: ${PRODUCT_DATABASE_URL}
      PORT: ${PRODUCT_SERVICE_PORT}
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.products.rule=PathPrefix(`/api/products`)"
      - "traefik.http.routers.products.middlewares=products-strip@docker"
      - "traefik.http.middlewares.products-strip.stripprefix.prefixes=/api/products"
      - "traefik.http.services.products.loadbalancer.server.port=5001"
      - "traefik.docker.network=traefik-project_web"

    networks:
      - web
      - backend

  order-service:
    build:
      context: ./order-service
    environment:
      DATABASE_URL: ${ORDER_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      PRODUCT_SERVICE_URL: ${PRODUCT_SERVICE_URL}
      PORT: ${ORDER_SERVICE_PORT}
    depends_on:
      - postgres
      - redis
      - user-service
      - product-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orders.rule=PathPrefix(`/api/orders`)"
      - "traefik.http.routers.orders.middlewares=orders-strip@docker"
      - "traefik.http.middlewares.orders-strip.stripprefix.prefixes=/api/orders"
      - "traefik.http.services.orders.loadbalancer.server.port=5002"
      - "traefik.docker.network=traefik-project_web"

    networks:
      - web
      - backend

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - backend

  redis:
    image: redis:7-alpine
    networks:
      - backend

volumes:
  postgres_data:

networks:
  web:
    driver: bridge
  backend:
    driver: bridge
